lol/urls.py
from django.contrib import admin
from django.urls import path,include
<<<<<<< HEAD
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('todo.urls', namespace='notes')),
=======
from lol import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.LandingView.as_view() , name='landing' ),
    path('notes/', include('todo.urls',namespace='notes')),
    path('urlshortner', include('urlshortner.urls',namespace='urlshortner')),
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/register/', views.register_view, name='register'),
>>>>>>> develop
]

todo/urls.py
<<<<<<< HEAD
from django.urls import path
from . import views
from .views import home, login_view, register_view, logout_view, note_detail, edit_note, delete_note, LandingView
from django.conf import settings
from django.conf.urls.static import static

=======
from django.urls import path,include
from todo import views
>>>>>>> develop

app_name = 'notes'

urlpatterns = [

    #home page and dashboard
<<<<<<< HEAD
    path('', LandingView.as_view() , name='landing' ),
    path('notes/mine/', home, name='home' ),
    path('accounts/login/', login_view, name='login'),
    path('accounts/logout/', logout_view, name='logout'),
    path('accounts/register/', register_view, name='register'),
    path('<slug:slug>/<int:pk>/', note_detail, name='note_detail'),
    path('edit/note/<slug:slug>/<int:pk>', edit_note, name='edit_note'),
    path('delete/note/<slug:slug>/<int:pk>', delete_note, name='note_confirm_delete'),


    
]
if settings.DEBUG:
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
=======
    path('', views.home, name='home' ),
    path('<slug:slug>/<int:pk>/', include([
        path('',views.note_detail, name='note_detail'),
        path('edit', views.edit_note, name='edit_note'),
        path('delete', views.delete_note, name='note_confirm_delete')
        ])),
]
>>>>>>> develop

urlshortner/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import CreateShortenedLink,RedirectLink
app_name  = 'urlshortner'

urlpatterns = [
    path('', CreateShortenedLink.as_view() , name='shortner'),
    path('<str:attach>/', RedirectLink.as_view()),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
      <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="generator" content="Jekyll v3.8.5">
        {% load static %}



        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


        <link rel="stylesheet" type="text/css" href="{% static 'boot/css/style.css' %}"/>
        <meta charset="utf-8">

        <title>
            {% block title %} lol {% endblock %}
        </title>
    </head>

<body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<<<<<<< HEAD
=======
    <nav class="navbar navbar-xs navbar-expand-sm navbar-dark bg-dark " style="padding-top:    0.25rem; /* 0px does not look good on small screens */
    padding-bottom: 0.25rem;
    font-size: smaller;      /* Just because I am using big size font */
    line-height: 1em;">
        <a class="navbar-brand" href="#">lol</a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="navbarsExample09" style="">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% comment %}
                {% url 'notes:home' current_user.username %}
              {% endcomment %}">Noteboard <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'urlshortner:shortner' %}">Url-Shortner <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown09" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">More</a>
              <div class="dropdown-menu" aria-labelledby="dropdown09">
                <a class="dropdown-item" href="#">About</a>
                {% if request.user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                {% else %}
                  <a class="dropdown-item" href="{% url 'register' %}">register</a>
                  <a class="dropdown-item" href="{% url 'login' %}">login</a>
                {% endif %}
              </div>
            </li>
          </ul>

        </div>
      </nav>    <br>
>>>>>>> develop

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark nav-masthead">
        <div class="container">
          <a class="navbar-brand" href="#"> <h3 class="masthead-brand mb-0"><i class="fas fa-fire-alt"></i></h3></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link p-2 font-weight-bold text-white" href="{% url 'notes:landing' %}">Home </a>
              </li>
              <li class="nav-item">
                <a class="nav-link p-2 font-weight-bold text-white" href="#">Products</a>
              </li>
              <li class="nav-item">
                <a class="nav-link font-weight-bold p-2 text-white" href="#">About</a>
              </li>
            </ul>
            {% if request.user.is_authenticated %}

            <a class="nav-link font-weight-bold p-2 text-white" href="{% url 'notes:logout' %}">Logout</a>
            <a class="nav-link font-weight-bold p-2 text-white" href="{% url 'notes:home' request.user.username %}">notesboard</a>
            {% else %}
            <a class="nav-link text-white p-2 font-weight-bold" href="{% url 'notes:login' %}">Login</a>
            <a class="nav-link text-white p-2 font-weight-bold" href="{% url 'notes:register' %}">Register</a>
            {% endif %}



          </div>
          </div>
        </nav>




    <br>




{% block body %}

{% endblock body %}



    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/create_url.html
{% extends 'base.html' %}

{% block title %}login|{% endblock %}

{% load static %}




{% block body %}



<body class="bg-light">

<div class="container login">
            <div class="col-sm-4 offset-md-4">


                    <div class="row">
                    <h1 class="h3 mb-3 font-weight-normal">Shorten Your url</h1>

                      {% if messages %}
                      <ul class="messages">
                          {% for message in messages %}
                          <div class="alert alert-success" role="alert">
                            <li {% if message.tags %} class="{{message.tags}}"{% endif %}>{{ message }}</li>
                          </div>
                          {% endfor %}

                      </ul>
                      {% endif %}
                      <div class="">

                        <form method="POST">
                              {% csrf_token %}
                              {% for field in form %}
                              <div class="form-group">
                                  {{ field.error }}
                                  {{ field.label_tag }}
                                  <div class="form-control">
                                    {{ field }}
                                  </div>
                              </div>
                              {% endfor %}
                          <button class="btn btn-primary btn-lg btn-block" type="submit">Save Note</button>
                        </form>
                      </div>
                    </div>
            </div>
    </div>
</body>
{% endblock body %}

templates/dashboard.html
{% extends 'base.html' %}

{% block title %}{{request.user}} | noteboard{% endblock %}

{% load static %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

{% block body %}
<body class="bg-light">

        <div class="container">
          <div class="py-5 text-center">
            <!-- <img class="d-block mx-auto mb-4" src=" " alt="" width="72" height="72"> -->
            <h5>{{current_user.username}}'s noteboard</h5>
            <p class="lead">Welcome to your dashboard, Remember to always jott a Note before leaving... it helps !!!</p>
          </div>

          <div class="row">
            <div class="col-md-4 order-md-2 mb-4">
              <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Your Notes</span>

                <span class="badge badge-secondary badge-pill">{{note.count}}</span>
              </h4>
              {% for mynotes in note %}
              <ul class="list-group mb-3">
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                  <div>
                    <h6 class="my-0">{{ mynotes.title }}</h6>
                    <small class="text-muted">{{ mynotes.note|slice:":50" }}...<a href="{% url 'notes:edit_note' mynotes.slug mynotes.pk %}">read more</a></small><br>
                    <small>{{ mynotes.date }}</small>
                  </div>

                </li>

              </ul>
              {% endfor %}


            </div>

            <div class="col-md-8 order-md-1">
              
              {% if messages %}             
              <ul class="messages">
                
                  {% for message in messages %}
                  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                  </div>
                {% endfor %}
                  
                
              </ul>
              {% endif %}
              <h4 class="mb-3">Write Note</h4>
              <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.label_tag }}
                        {{ field }}

                    </div>
                    {% endfor %}
                <button class="btn btn-primary btn-lg btn-block" type="submit">Save Note</button>
              </form>
            </div>
          </div>

          <footer class="my-5 pt-5 text-muted text-center text-small">
            <p class="mb-1">© 2020-2021 lol</p>
            <ul class="list-inline">
              <li class="list-inline-item"><a href="#">Privacy</a></li>
              <li class="list-inline-item"><a href="#">Terms</a></li>
              <li class="list-inline-item"><a href="#">Support</a></li>
            </ul>
          </footer>
        </div>

        <script>
          // Example starter JavaScript for disabling form submissions if there are invalid fields
          (function() {
            'use strict';

            window.addEventListener('load', function() {
              // Fetch all the forms we want to apply custom Bootstrap validation styles to
              var forms = document.getElementsByClassName('needs-validation');

              // Loop over them and prevent submission
              var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                  if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                  }
                  form.classList.add('was-validated');
                }, false);
              });
            }, false);
          })();
        </script>


    </body>


{% endblock body %}

templates/edit_note.html
{% extends 'base.html' %}

{% block title %}edit | {{note.title}}{% endblock %}

{% load static %}



{% block body %}


<body class="bg-light">
<div class="container">
    <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">

        <div class="row">
            <div class="col-md-6 px-0">
                <h1 class="display-4 font-italic">{{note.title}}</h1>
                <h6>{{note.note}}</h6>
                <small><p>{{note.date}}</p></small>
            </div>


            <div class="col-md-6">
                {% if messages %}             
                <ul class="messages">
                  
                    {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                      {{ message }}
                    </div>
                    {% endfor %}
                    
                    
                    </ul>
                    {% endif %}
                            <div class="card flex-md-row mb-4 box-shadow h-md-250">
                              <div class="card-body d-flex flex-column ">

                                <h3 class="mb-0 text-dark align-items-center">
                                  Edit Note
                                </h3>
                                
                                <form method="POST">
                                      {% csrf_token %}
                                      {% for field in form %}
                                      <div class="form-group">
                                          {{ field.errors }}
                                          {{ field.label_tag }}
                                          {{ field }}
                                      </div>
                                      {% endfor %}
                                      <input type="submit" class="btn btn-primary" value="submit"/>
                                      <a href="{% url 'notes:note_confirm_delete' note.slug note.pk %}"
                                      type='button'
                                      class="btn btn-danger">delete
                                      </a>
                                  </form>
                              </div>
                            </div>
                          </div>
            </div>
            </div>
            </div><br>


            </div>


        </div>


          </div>
        </body>
        {% endblock body %}

        <div class="row mb-2">
                <div class="col-md-6">
                  <div class="card flex-md-row mb-4 box-shadow h-md-250">
                    <div class="card-body d-flex flex-column align-items-start">
                      <strong class="d-inline-block mb-2 text-primary">World</strong>
                      <h3 class="mb-0">
                        <a class="text-dark" href="#">Featured post</a>
                      </h3>
                      <div class="mb-1 text-muted">Nov 12</div>
                      <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                      <a href="#">Continue reading</a>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="card flex-md-row mb-4 box-shadow h-md-250">
                    <div class="card-body d-flex flex-column align-items-start">
                      <strong class="d-inline-block mb-2 text-success">Design</strong>
                      <h3 class="mb-0">
                        <a class="text-dark" href="#">Post title</a>
                      </h3>
                      <div class="mb-1 text-muted">Nov 11</div>
                      <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                      <a href="#">Continue reading</a>
                    </div>
                  </div>
                </div>
              </div>

templates/login.html
{% extends 'base.html' %}

{% block title %}login|{% endblock %}

{% load static %}

{% block body %}



<body class="bg-light">

<div class="container login">
            <div class="col-sm-4 offset-md-4">


                <div class="text-center mb-4">

                    <h1 class="h3 mb-3 font-weight-normal">Login</h1>

                    </div>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{message.tags}}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <form action = "" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for='username'>username</label>
                        <input type='text' class='form-control' name = 'username' placeholder="Enter username">
                    </div>

                    <div class="form-group">
                            <label for='password'>password</label>
                            <input type='password' class='form-control' name = 'password' placeholder="Enter password">
                        </div>
                        <div class="checkbox mb-3">
                              <label>
                                <input type="checkbox" value="remember-me"> Remember me
                              </label>
                            </div>
                            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
                            <p class="mt-5 mb-3 text-muted text-center">© 2017-2018</p>
                </form>
                <p>dont have an account?  <a href="{% url 'register' %}">register</a> </p>
            </div>
    </div>
</body>
{% endblock body %}

templates/note_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
    <head>
      <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="generator" content="Jekyll v3.8.5">
        {% load static %}

        

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


        <link rel="stylesheet" type="text/css" href="{% static 'boot/css/style.css' %}"/>
        <meta charset="utf-8">

        <title>
           confirm delete
        </title>
    </head>

<body>
        <body class="bg-light">

            </body>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>




<div class="container">
    <div class="container">
            <form action="" method='POST'>
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger" value="you sure about this">
                    
                </form>
    </div>
</div>

templates/note_detail.html
{% extends 'base.html' %}

{% block title %}note | {{note.title}}{% endblock %}

{% load static %}



{% block body %}
<body class="bg-light">
    </body>
<div class="container">
    <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
            <div class="col-md-6 px-0">
              <h1 class="display-4 font-italic">{{note.title}}</h1>
                <small><h6>{{note.note}}</h6></small>

            </div><br>
            <small><p>{{note.date}}</p></small>
          </div>

        </div>

          </div>
        </body>
{% endblock body%}

templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Register|{% endblock %}

{% load static %}




{% block body %}
<body class="bg-light">
    <div class="container">
        <div class="row">

            <div class="col-sm-6 offset-sm-3">


                    <h1>Register</h1>
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{message.tags}}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}


                        <form method="POST">

                            {% csrf_token %}
                            {% for field in form %}
                            <div class="form-group">
                                {{ field.errors }}
                                {{ field.label_tag }}
                                {{ field }}
                            </div>
                            {% endfor %}
                            <input type="submit" class="btn btn-primary" value="submit"/>
                        </form>
                        <p>already have an account?  <a href="{% url 'login' %}">login</a> </p>
            </div>
        </div>
    </div>
</body>
{% endblock body %}